src/Entity/Medicament.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MedicamentRepository")
 * @Vich\Uploadable()
 */
class Medicament
{

    const TYPES = [
        0 => 'Non défini',
        1 => 'Antibiotique',
        2 => 'Divers',
        3 => 'Soin du corps'
    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var File|null
     * @Assert\Image(
     *     mimeTypes="image/jpeg")
     *
     * @Vich\UploadableField(mapping="medicament_image", fileNameProperty="picture")
     */
    private $imageFile;

    /**
     * @Assert\Length(
     *     min = 5,
     *     max = 50,
     *     minMessage = "{{ limit }} caractères minimum pour le titre du médicament)",
     *     maxMessage = "{{ limit }} caractères maximum pour le nom du médicament"
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $notice;


    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $enable = true;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $commentaires;


    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Symptome", inversedBy="medicaments")
     */
    private $symptomes;

    /**
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CatMedicaments", inversedBy="medicament")
     * @ORM\JoinColumn(nullable=true)
     */
    private $catMedicament;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\GroupsMedic", inversedBy="medicaments")
     * @ORM\JoinColumn(nullable=true)
     */
    private $GroupMedicament;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Famille", inversedBy="medicaments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $famille;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Products", mappedBy="medicament", orphanRemoval=true)
     */
    private $products;




    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->symptomes = new ArrayCollection();
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): string
    {
        $slugify = new Slugify();
        return $slugify->slugify($this->name);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNotice(): ?string
    {
        return $this->notice;
    }

    public function setNotice(?string $notice): self
    {
        $this->notice = $notice;

        return $this;
    }


    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getEnable(): ?bool
    {
        return $this->enable;
    }

    public function setEnable(bool $enable): self
    {
        $this->enable = $enable;

        return $this;
    }

    public function getCommentaires(): ?string
    {
        return $this->commentaires;
    }

    public function setCommentaires(?string $commentaires): self
    {
        $this->commentaires = $commentaires;

        return $this;
    }

    /**
     * @return Collection|symptome[]
     */
    public function getSymptomes(): Collection
    {
        return $this->symptomes;
    }

    public function addSymptome(symptome $symptome): self
    {
        if (!$this->symptomes->contains($symptome)) {
            $this->symptomes[] = $symptome;
        }

        return $this;
    }

    public function removeSymptome(symptome $symptome): self
    {
        if ($this->symptomes->contains($symptome)) {
            $this->symptomes->removeElement($symptome);
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Medicament
     */
    public function setImageFile(?File $imageFile): Medicament
    {
        $this->imageFile = $imageFile;

        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCatMedicament(): ?CatMedicaments
    {
        return $this->catMedicament;
    }

    public function setCatMedicament(?CatMedicaments $catMedicament): self
    {
        $this->catMedicament = $catMedicament;

        return $this;
    }

    public function getGroupMedicament(): ?GroupsMedic
    {
        return $this->GroupMedicament;
    }

    public function setGroupMedicament(?GroupsMedic $GroupMedicament): self
    {
        $this->GroupMedicament = $GroupMedicament;

        return $this;
    }

    public function getFamille(): ?Famille
    {
        return $this->famille;
    }

    public function setFamille(?Famille $famille): self
    {
        $this->famille = $famille;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * @return Collection|Products[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Products $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setMedicament($this);
        }

        return $this;
    }

    public function removeProduct(Products $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getMedicament() === $this) {
                $product->setMedicament(null);
            }
        }

        return $this;
    }









}

src/Entity/Products.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductsRepository")
 */
class Products
{
    public function __construct(){
        $this->createdAt = new \DateTime();
        $this->state = 0;
    }

    const STATES = [
        0 => 'Neuf',
        1 => 'Ouvert',
        2 => 'Presque vide'
    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Medicament", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $medicament;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Famille", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $famille;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantity;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $state;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $expire;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Locations", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $location;

    /**
     * @ORM\Column(type="integer")
     */
    private $initialQuantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMedicament(): ?Medicament
    {
        return $this->medicament;
    }

    public function setMedicament(?Medicament $medicament): self
    {
        $this->medicament = $medicament;

        return $this;
    }

    public function getFamille(): ?Famille
    {
        return $this->famille;
    }

    public function setFamille(?Famille $famille): self
    {
        $this->famille = $famille;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getStateName(): string
    {
       return self::STATES[$this->state];
    }

    public function getExpire(): ?\DateTimeInterface
    {
        return $this->expire;
    }

    public function setExpire(?\DateTimeInterface $expire): self
    {
        $this->expire = $expire;

        return $this;
    }

    public function getLocation(): ?Locations
    {
        return $this->location;
    }

    public function setLocation(?Locations $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getInitialQuantity(): ?int
    {
        return $this->initialQuantity;
    }

    public function setInitialQuantity(int $initialQuantity): self
    {
        $this->initialQuantity = $initialQuantity;

        return $this;
    }
}

src/Controller/MedicamentController.php
<?php
/**
 * Created by PhpStorm.
 * User: Seb
 * Date: 26/04/2019
 * Time: 10:29
 */

namespace App\Controller;


use App\Entity\Medicament;
use App\Entity\MedicamentFilter;
use App\Entity\Products;
use App\Form\MedicamentFilterType;
use App\Form\ProductType;
use App\Repository\MedicamentRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MedicamentController extends AbstractController
{
    /**
     * @var
     */
    private $repository;
    /**
     * @var
     */
    private $em;

    public function __construct(MedicamentRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/dash/medicaments", name="dash.medicament.index")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        if(!$this->getUser()->getFamille()){
            return $this->redirectToRoute("dash.familles.init");
        }
        //On ajoute le formulaire de recherche et on le passe en argument à la requette
        $search = new MedicamentFilter();
        $form = $this->createForm(MedicamentFilterType::class, $search, [
            'famille' => $this->getUser()->getFamille()
        ]);
        $form->handleRequest($request);

        //on récupère la requette SQL dans le repository
        $queryMedicament = $this->repository->findAllEnableQuery($search, $this->getUser()->getFamille());

        //On utilise le bundle Paginator KNP
        $medicament = $paginator->paginate(
            $queryMedicament,
            $request->query->getInt('page', 1),
            10
        );



        return $this->render("medicaments/index.html.twig", [
            "current_menu" => "medicaments",
            "medicaments" => $medicament,
            'form' => $form->createView()
        ]);

    }

    /**
     * @Route("/dash/medicaments/{slug}-{id}", name="dash.medicament.detail", requirements={"slug": "[a-z0-9\-]*"})
     * @return Response
     */
    public function detail($slug, Medicament $medicament, Request $request): Response
    {
        if(!$this->getUser()->getFamille()){
            return $this->redirectToRoute("dash.familles.init");
        }
        //$medicament = $this->repository->find($id);
        ///*A la place de mettre $id en argument et de faire une recherche avec la méthode find comme ci-dessus,
        /// on peut faire une injection de l'entity Medicament, etant donné que symfony trouve un id, symfony va faire
        /// la recherche à notre place
$newProduct = new Products();
        //$form = $this->createForm(ProductType::class, $medicament);

        if ($medicament->getSlug() !== $slug) {
            return $this->redirectToRoute("dash.medicament.detail", [
                "id" => $medicament->getId(),
                "slug" => $medicament->getSlug()
            ], 301);
        }
        $form = $this->createForm(ProductType::class, $newProduct, [
            'famille' => $this->getUser()->getFamille(),
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $newProduct->setFamille($this->getUser()->getFamille());
            $newProduct->setMedicament($medicament);
            $newProduct->setQuantity($medicament->getQuantity());
            $newProduct->setInitialQuantity($medicament->getQuantity());
            $this->em->persist($newProduct);
            $this->em->flush();
            $this->addFlash('success', 'Le médicament a bien été ajouté');
            //return $this->redirectToRoute("admin.medicaments.detail");
        }

        return $this->render("medicaments/detail.html.twig", [
            "medicament" => $medicament,
            "current_menu" => "medicaments",
            "slug" => $slug,
            "form" => $form->createView()
        ]);
    }


}

templates/medicaments/detail.html.twig
{% extends "base.html.twig" %}

{% block title %}
    {{ medicament.name }}
{% endblock %}

{% block body %}

    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}

    <div class="container mt-5">
        <div class="shadow p-4 bg-light rounded border" style="min-height: 650px">


            <div class="row align-middle">
                <div class="col-lg-9 text-center ">
                    <span class="align-middle">
                    <h2 class="mb-2">{{ medicament.name }}</h2>
                        <span class=" nav-item nav-link badge badge-secondary">{% if medicament.catMedicament %} {{ medicament.catMedicament.name }}{% endif %}</span>
                        <span class=" nav-item nav-link badge badge-secondary">{% if medicament.catMedicament %} {{ medicament.groupMedicament.name }}{% endif %}</span>
                    </span>
                </div>
                <div class="col-lg-3 d-flex justify-content-end">
                    {% if medicament.picture %}
                        <img src="{{ vich_uploader_asset(medicament, 'imageFile') | imagine_filter('thumb') }}"
                             alt="card-img-top ">
                    {% else %}
                        <img src="{{ '/images/medicaments/empty.jpg' | imagine_filter('thumb') }}" alt="card-img-top"
                             style="width: 100%; height:auto;">
                    {% endif %}
                </div>
            </div>


            <div class="row">
                <div class="col-lg-10">
                    <nav class="mb-3 ">
                        <div class="nav nav-tabs" id="nav-tab" role="tablist">
                            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-stock"
                               role="tab" aria-controls="nav-stock" aria-selected="true">Produits</a>
                            <a class="nav-item nav-link" id="nav-home-tab" data-toggle="tab" href="#nav-home"
                               role="tab" aria-controls="nav-home" aria-selected="true">Description</a>
                            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile"
                               role="tab" aria-controls="nav-profile" aria-selected="false">Commentaire</a>

                        </div>
                    </nav>
                    <div class="tab-content" id="nav-tabContent">

                        <div class="tab-pane fade" id="nav-home" role="tabpanel"
                             aria-labelledby="nav-home-tab">
                            {{ medicament.description |nl2br }}
                        </div>

                        <div class="tab-pane fade show active" id="nav-stock" role="tabpanel"
                             aria-labelledby="nav-home-tab">


                            <table class="table table-sm">
                                <thead>
                                <tr>
                                    <th scope="col">Date d'ajout</th>
                                    <th scope="col">Date d'expiration</th>
                                    <th scope="col">Emplacement</th>
                                    <th scope="col" class="text-center">Stock</th>
                                    <th scop="col" class="text-center">Action</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% for product in medicament.products %}
                                    <tr class="tablerowhref"
                                        data-href="{{ path('dash.product.edit', {id: product.id }) }}">
                                        <td>{{ product.createdAt|localizeddate('none', 'none', null, null, "d MMMM Y") }}</td>
                                        <td>{{ product.expire|localizeddate('none', 'none', null, null, "MMMM Y") }}</td>
                                        <td>{{ product.location.parent.name }} -> {{ product.location.name }}</td>
                                        <td class="text-center">
                                            {% if(product.initialQuantity != -1) %}
                                                {% if(product.quantity ==  product.initialQuantity) %}<span class="badge badge-pill badge-success pt-1">
                                                {% elseif (product.quantity <  product.initialQuantity / 2)%}<span class="badge badge-pill badge-warning pt-1">
                                                {% elseif (product.quantity <  product.initialQuantity) %}<span class="badge badge-pill badge-secondary pt-1">
                                                    {% endif %}
                                                {{ product.quantity }} / {{ product.initialQuantity }}
                                                    </span>
                                            {% else %}
                                                {{ product.stateName }}
                                            {% endif %}
                                        </td>

                                        <td class="text-right">
                                            <form method="post"
                                                  action="{{ path('dash.product.substring', {id: product.id}) }}"
                                                  style="display: inline-block"
                                                  onsubmit="return confirm('Vous êtes sur le point de diminuer la quantité')">
                                                <input type="hidden" name="_method" value="SUBSTRING">
                                                <input type="hidden" name="_token"
                                                       value="{{ csrf_token('substring' ~ product.id) }}">

                                                    {% if(product.initialQuantity != -1) %}
                                                <button class="btn btn-primary btn-sm">
                                                        - 1
                                                </button>
                                                    {% else %}
                                                        {% if(product.state == 0) %}
                                                            <button class="btn btn-primary btn-sm">
                                                            Passer à boite ouverte
                                                            </button>
                                                            {% elseif (product.state == 1) %}
                                                                <button class="btn btn-primary btn-sm">
                                                            Passer à presque vide
                                                                </button>
                                                            {% endif %}
                                                    {% endif %}

                                            </form>
                                            <form method="post" action="{{ path('dash.product.delete', {id: product.id}) }}"
                                                  style="display: inline-block"
                                                  onsubmit="return confirm('Vous êtes sur le point de supprimer le produit')">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token"
                                                       value="{{ csrf_token('delete' ~ product.id) }}">

                                                <button type="submit" class="btn btn-danger btn-sm">
                                                    <span class="icon trash"></span>
                                                </button>
                                            </form>


                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>


                            <button type="button" class="btn btn-outline-primary" data-toggle="modal"
                                    data-target="#ajout">
                                Ajouter
                            </button>
                        </div>
                        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">

                            {{ medicament.commentaires |nl2br }}
                        </div>

                    </div>
                </div>
                <div class="col-lg-2 mt-5 text-center">
                    <h6>Symptomes</h6>
                    <div class="dropdown-divider"></div>
                    {% for symptome in medicament.Symptomes %} <span
                            class="badge badge-success">{{ symptome.name }}</span></br>{% endfor %}
                </div>

            </div>
        </div>

    </div>


    <div class="modal fade" id="ajout" tabindex="-1" role="dialog" aria-labelledby="Ajout d'un produit"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ajout d'un produit</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    {{ form_start(form) }}

                    {{ form_rest(form) }}


                    <button class="btn btn-primary">{{ button|default('Ajouter') }}</button>
                    {{ form_end(form) }}

                </div>

            </div>
        </div>
    </div>
{% endblock %}

templates/medicaments/index.html.twig
{% extends "base.html.twig" %}

{% block title "Liste des médicaments" %}
{% block body %}

    <div class="container-fluid mt-4 ">
        <h1 class="text-center">Liste des médicaments</h1>


        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-2 ">

                <div class="border p-3">
                    <div class="bg-light p-2">
                        <p class="text-center">Appliquer un filtre</p>
                        <div class="dropdown-divider"></div>

                    </div>
                    {{ form_start(form) }}

                    <div class="form-group">

                            {{ form_row(form.catMedic) }}

                        </div>
                        <div class="form-group">
                            {{ form_row(form.groupMedic) }}
                        </div>

                    <div class="form-group">
                            {{ form_row(form.symptomes) }}
                        </div>

                            <div class="form_group">
                                <button type="submit" class="btn btn-primary">Filtrer</button>
                            </div>

                    </div>
                </div>


            {{ form_end(form) }}



            <div class="col-12 col-sm-12 col-md-12 col-lg-10 ">


                <div class="card-group">


                    {% for element in medicaments %}
                        <div class="p-2">


                            <div class="card" style="width: 15rem; height:15rem; overflow:hidden">
                                {% if element.picture %}
                                    <img src="{{ vich_uploader_asset(element, 'imageFile') | imagine_filter('thumb') }}"
                                         alt="card-img-top" style=" height:auto;   margin-left: auto;
  margin-right: auto;
  display: block;">
                                {% else %}
                                    <img src="{{ '/images/medicaments/empty.jpg' | imagine_filter('thumb') }}"
                                         alt="card-img-top" style="width: 100%; height:auto;">
                                {% endif %}

                                <div class="card-body">
                                    <a href="{{ path('dash.medicament.detail', {id: element.id, slug: element.slug}) }}" class="btn btn-primary">
                                        {{ element.name }} <span class="badge badge-light">{{ element.products|length }}</span>
                                    </a>
                                    <div class="mt-1 text-center">
                                    {% for symptome in element.Symptomes %} <span class="badge badge-success">{% if loop.index == 1 or loop.index == 2%}{{ symptome.name }}{% endif %}{% if loop.index == 3 %}. . .{% endif %}</span>{% endfor %}
                                </div>
                                    <div class=" text-center">
                                        <span class="badge badge-secondary">{{ element.groupMedicament.name }}</span>
                                    </div>
                                </div>
                            </div>


                    </div>
                    {% endfor %}

                </div>
                <div class="navigation">
                    {{ knp_pagination_render(medicaments) }}
                </div>

            </div>
        </div>


    </div>
{% endblock %}